### ISSUE TITLE
forbidden namespace prefixes should be checked

### ISSUE THREAD

**Issue by tobyink** [kjetilk/URI-NamespaceMap#1]
The pod says...

> Avoid using the names 'can', 'isa', 'VERSION', and 'DOES' as namespace prefix, because these names are defined as method for every Perl object by default. The method names 'new' and 'uri' are also forbidden. Names of methods of Moose::Object must also be avoided.

The `add_namespace` method and the constructor should check that you're not using any of these "naughty" prefixes, and carp (or croak) if you try.

**Comment by kjetilk** [comment]
All fixed now! :-)

1.0 release is pending.
