### ISSUE TITLE
t/prefixguess-none.t may fail

### ISSUE THREAD

**Issue by eserte** [kjetilk/URI-NamespaceMap#10]
See http://matrix.cpantesters.org/?dist=URI-NamespaceMap%200.26 for a fail/pass overview.
Unfortunately I cannot give more information here, except that in almost all cases `t/prefixguess-none.t` failed (see http://analysis.cpantesters.org/solved?distv=URI-NamespaceMap-0.26 ).

**Comment by kjetilk** [comment]
Thanks a lot for the heads up! I feel kinda crippled when it is not sending me emails... I'll have a look!

**Comment by kjetilk** [comment]
OK, I have released 0.27_01 to CPAN. I hope it fixes the problem. 
The problem occured if none of the optional modules, RDF::NS::Curated, XML::CommonNS, RDF::NS or RDF::Prefixes were installed, and it is not terribly easy to modify the environment all the time to test for that, so I have relied on cpantesters to tell me when it breaks. Great if you test and let me know! :-)

Cheers, 

Kjetil

**Comment by kjetilk** [comment]
I have released 0.28 to CPAN, after all tests have passed there too for a day. :-) So, I betting it is fixed.

Cheers,

Kjetil
