### ISSUE TITLE
lib/Types/Namespace.pm POD descibes Types::URI

### ISSUE THREAD

**Issue by ppisar** [kjetilk/URI-NamespaceMap#15]
DESCRIPTION section in Types::Namespace POD reads:

```
Types::URI is a type constraint library suitable for use with Moo/Moose
attributes, Kavorka sub signatures, and so forth.
```

I think this is a copy-and-paste mistake. It should read Types::Namespace instead of Types::URI.

**Comment by kjetilk** [comment]
Yeah, I think you're right! Let me see if I can find a second.
